-- Loaded ONLY by the 'local' Spring profile (spring.sql.init.platform=h2).
-- The application mints unique numeric ids via SELECT nextval('url_mapping_seq');
-- in production that sequence is created by the Flyway migration, but the local H2
-- profile disables Flyway, so we create the sequence here. The table itself is
-- generated by Hibernate (ddl-auto: create-drop).
CREATE SEQUENCE IF NOT EXISTS url_mapping_seq START WITH 1000000 INCREMENT BY 1;
